package com.myspace.washit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CheckPickupAndDeliveryTaskHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CheckPickupAndDeliveryTaskHandler() {
    }




}