package com.myspace.washit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CheckLoginDataTaskHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CheckLoginDataTaskHandler() {
    }




}