package com.myspace.washit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DeleteCustomerTaskHandler implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DeleteCustomerTaskHandler() {
    }




}