package com.myspace.washit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Shirts")
	private java.lang.Boolean shirts;

	public Order() {
	}

	public java.lang.Boolean getShirts() {
		return this.shirts;
	}

	public void setShirts(java.lang.Boolean shirts) {
		this.shirts = shirts;
	}

	public Order(java.lang.Boolean shirts) {
		this.shirts = shirts;
	}

}